CREATE TABLE Concessionaria 
( 
 ID SERIAL PRIMARY KEY,  
 NOME VARCHAR(50) NOT NULL
); 

CREATE TABLE Linha_Viagem 
( 
 idLinha INT,  
 idViagem INT,  
 ID SERIAL PRIMARY KEY  
); 

CREATE TABLE Passagem 
( 
 idTipo_Passagem INT,  
 ID SERIAL PRIMARY KEY
); 

CREATE TABLE Passageiro 
( 
 ID SERIAL PRIMARY KEY,  
 idUsuarios INT  
); 

CREATE TABLE Tipo_Passagem 
( 
 ID SERIAL PRIMARY KEY,  
 DESCRICAO VARCHAR(50) NOT NULL,  
 PRECO FLOAT NOT NULL  
); 

CREATE TABLE Nome_Empresa
(
 ID SERIAL PRIMARY KEY,
 NOME_FANTASIA VARCHAR(50) NOT NULL
);

CREATE TABLE Empresa 
( 
 ID SERIAL PRIMARY KEY,  
 CNPJ VARCHAR(15) NOT NULL,   
 idConcessionaria INT,
 idNome_Empresa INT,
 RAZAO_SOCIAL VARCHAR(50) NOT NULL
); 

CREATE TABLE Viagem 
( 
 ID SERIAL PRIMARY KEY,  
 DATA DATE NOT NULL,  
 idPassageiro INT  
); 

CREATE TABLE Tipo_Funcionario 
( 
 ID SERIAL PRIMARY KEY,  
 DESCRICAO VARCHAR(50) NOT NULL
); 

CREATE TABLE Veiculos_Viagem 
( 
 idViagem INT,  
 idVeiculos INT,  
 ID SERIAL PRIMARY KEY
); 

CREATE TABLE Roteiro 
( 
 ID SERIAL PRIMARY KEY  
); 

CREATE TABLE Pontos 
( 
 ID SERIAL PRIMARY KEY,  
 idENDERECOS INT
); 

CREATE TABLE Roteiros_Pontos 
( 
 ID SERIAL PRIMARY KEY,  
 idPontos INT,  
 idRoteiro INT 
); 

CREATE TABLE Funcionarios 
( 
 ID SERIAL PRIMARY KEY,  
 NOME VARCHAR(50) NOT NULL,  
 CPF VARCHAR(15) NOT NULL,  
 RG VARCHAR(15) NOT NULL,  
 DATA_NASCIMENTO DATE NOT NULL,  
 DATA_CONTRATACAO DATE NOT NULL,  
 idTipo_Funcionario INT NOT NULL
); 

CREATE TABLE Veiculos 
( 
 ID SERIAL PRIMARY KEY,  
 PLACA VARCHAR(10) NOT NULL, 
 CHASSI VARCHAR(20),
 idDescricao_veiculo INT,  
 idEmpresa INT
); 

CREATE TABLE Funcionarios_Viagem 
( 
 ID SERIAL PRIMARY KEY,  
 idFuncionarios INT,  
 idViagem INT  
); 

CREATE TABLE Linha 
( 
 ID SERIAL PRIMARY KEY,
 NOME VARCHAR(30),
 NUMERO VARCHAR(15), 
 idRoteiro INT  
); 

CREATE TABLE Passagem_Viagem 
( 
 ID SERIAL PRIMARY KEY,  
 idViagem INT,  
 idPassagem INT  
); 

CREATE TABLE ENDERECOS 
( 
 ID SERIAL PRIMARY KEY,  
 CEP VARCHAR(15) NOT NULL,  
 RUA VARCHAR(50) NOT NULL,  
 BAIRRO VARCHAR(50) NOT NULL,  
 PONTO_REFERENCIA VARCHAR(50)  
); 

CREATE TABLE Descricao_veiculo 
( 
 ID SERIAL PRIMARY KEY,  
 AR_CONDICIONADO CHAR(1) NOT NULL,  
 ANO DATE NOT NULL,  
 idMODELOS_VEICULOS INT,
 ULTIMA_MANUTENCAO  
); 

CREATE TABLE MODELOS_VEICULOS 
( 
 ID SERIAL PRIMARY KEY,  
 NOME VARCHAR(50) NOT NULL,  
 POTENCIA VARCHAR(10) NOT NULL,  
 TORQUE VARCHAR(10) NOT NULL,  
 CARGA_MAX FLOAT NOT NULL  
); 

CREATE TABLE CARTAO 
( 
 ID SERIAL PRIMARY KEY,  
 NUMERO_CARTAO INT NOT NULL,  
 SALDO FLOAT NOT NULL,  
 ATIVO CHAR(1) NOT NULL,  
 idUsuarios INT,  
 idTipo_Passagem INT,  
 idStatus_Cartao INT  
); 

CREATE TABLE Usuarios 
( 
 id SERIAL PRIMARY KEY,  
 CPF VARCHAR(15),  
 RG INT,  
 DATA_NASCIMENTO DATE  
); 

CREATE TABLE Status_Cartao 
( 
 ID SERIAL PRIMARY KEY,  
 DESCRICAO VARCHAR(50) NOT NULL
); 


ALTER TABLE Linha_Viagem ADD FOREIGN KEY(idLinha) REFERENCES Linha (ID);
ALTER TABLE Linha_Viagem ADD FOREIGN KEY(idViagem) REFERENCES Viagem (ID);
ALTER TABLE Passagem ADD FOREIGN KEY(idTipo_Passagem) REFERENCES Tipo_Passagem (ID);
ALTER TABLE Passageiro ADD FOREIGN KEY(idUsuarios) REFERENCES Concessionaria (ID);
ALTER TABLE Empresa ADD FOREIGN KEY(idConcessionaria) REFERENCES Concessionaria (ID);
ALTER TABLE Viagem ADD FOREIGN KEY(idPassageiro) REFERENCES Passageiro (ID);
ALTER TABLE Veiculos_Viagem ADD FOREIGN KEY(idViagem) REFERENCES Viagem (ID);
ALTER TABLE Veiculos_Viagem ADD FOREIGN KEY(idVeiculos) REFERENCES Veiculos (ID);
ALTER TABLE Pontos ADD FOREIGN KEY(idENDERECOS) REFERENCES ENDERECOS (ID);
ALTER TABLE Roteiros_Pontos ADD FOREIGN KEY(idPontos) REFERENCES Pontos (ID);
ALTER TABLE Roteiros_Pontos ADD FOREIGN KEY(idRoteiro) REFERENCES Roteiro (ID);
ALTER TABLE Funcionarios ADD FOREIGN KEY(idTipo_Funcionario) REFERENCES Concessionaria (ID);
ALTER TABLE Veiculos ADD FOREIGN KEY(idDescricao_veiculo) REFERENCES Descricao_veiculo (ID);
ALTER TABLE Veiculos ADD FOREIGN KEY(idEmpresa) REFERENCES Empresa (ID);
ALTER TABLE Funcionarios_Viagem ADD FOREIGN KEY(idFuncionarios) REFERENCES Funcionarios (ID);
ALTER TABLE Funcionarios_Viagem ADD FOREIGN KEY(idViagem) REFERENCES Viagem (ID);
ALTER TABLE Linha ADD FOREIGN KEY(idRoteiro) REFERENCES Roteiro (ID);
ALTER TABLE Passagem_Viagem ADD FOREIGN KEY(idViagem) REFERENCES Viagem (ID);
ALTER TABLE Passagem_Viagem ADD FOREIGN KEY(idPassagem) REFERENCES Passagem (ID);
ALTER TABLE Descricao_veiculo ADD FOREIGN KEY(idMODELOS_VEICULOS) REFERENCES MODELOS_VEICULOS (ID);
ALTER TABLE CARTAO ADD FOREIGN KEY(idUsuarios) REFERENCES Usuarios (id);
ALTER TABLE CARTAO ADD FOREIGN KEY(idTipo_Passagem) REFERENCES Tipo_Passagem (ID);
ALTER TABLE CARTAO ADD FOREIGN KEY(idStatus_Cartao) REFERENCES Status_Cartao (ID);
ALTER TABLE Empresa ADD FOREIGN KEY(idNome_Empresa) REFERENCES Nome_Empresa(ID);
